### ISSUE TITLE
Error in OBO export routine

### ISSUE THREAD

**Issue by pbuttigieg** [EcologicalSemantics/ecocore#10]
https://github.com/EcologicalSemantics/ecocore/blob/83e1ef267d39d70c185ee42133d9e23ddbe40d73/src/ontology/Makefile#L22-L23

@cmungall this relatively fresh OSK-sourced makefile is producing an error when trying to produce an OBO file from the OWL file (see below).

I think we bumped into this before in ENVO, and used owltools to handle this:

https://github.com/EnvironmentOntology/envo/blob/a4f69fe8ae5dd5ec6a1bc47563b8eacf7c2c15e6/src/envo/Makefile#L61-L62

Can ROBOT now do this without resorting to owltools?

```
ERROR MASKING ERROR ▒the axiom is not translated : SubClassOf(<http://purl.obolibrary.org/obo/ECOCORE_00000012> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> ObjectUnionOf(<http://purl.obolibrary.org/obo/ECOCORE_00000009> <http://purl.obolibrary.org/obo/ECOCORE_00000011>)))▒
java.lang.Exception
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2316)
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2308)
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:2047)
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:259)
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:228)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:57)
        at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:99)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:64)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1302)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:468)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:432)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:144)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:55)
ERROR error executing obo id to IRI
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI(OWLAPIObo2Owl.java:1664)
        at org.obolibrary.oboformat.writer.OBOFormatWriter$OWLOntologyNameProvider.getName(OBOFormatWriter.java:1182)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer$1.getName(OBOFormatRenderer.java:74)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:325)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:203)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:88)
        at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:99)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:64)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1302)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:468)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:432)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:144)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:55)
Caused by: java.lang.NullPointerException
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.translateShorthandIdToExpandedId(OWLAPIObo2Owl.java:1766)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI_load(OWLAPIObo2Owl.java:1705)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl$1.load(OWLAPIObo2Owl.java:81)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl$1.load(OWLAPIObo2Owl.java:77)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        ... 20 more
java.lang.NullPointerException
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.translateShorthandIdToExpandedId(OWLAPIObo2Owl.java:1766)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI_load(OWLAPIObo2Owl.java:1705)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI(OWLAPIObo2Owl.java:1670)
        at org.obolibrary.oboformat.writer.OBOFormatWriter$OWLOntologyNameProvider.getName(OBOFormatWriter.java:1182)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer$1.getName(OBOFormatRenderer.java:74)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:325)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:203)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:88)
        at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:99)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:64)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1302)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:468)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:432)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:144)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:55)

```

**Comment by marieALaporte** [comment]
The robot convert on the edit file works just fine. Robot does not bother about the union class. 
When I try to run robot reason on the file I got (ecocore-edit.obo), I got a different error: 
```
ERROR error executing obo id to IRI
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException

```

**Comment by cmungall** [comment]
https://github.com/ontodev/robot/issues/64
